<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Verify whether the registration buttion is displayed at right pannel top]]>
    </line>
    <line>
      <![CDATA[Registration buttion is successfully displayed at right pannel top]]>
    </line>
    <line>
      <![CDATA[Registration buttion is successfully clicked at right pannel top]]>
    </line>
    <line>
      <![CDATA[Without enter values in all the fields and clicked on submit button successfully]]>
    </line>
    <line>
      <![CDATA[Mandatory fields alert messages are successfully displayed]]>
    </line>
    <line>
      <![CDATA[Enter values in all the fields and clicked on submit button successfully]]>
    </line>
    <line>
      <![CDATA[Successfully Clicked on submit button]]>
    </line>
    <line>
      <![CDATA[Registration done successfully]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="20737" started-at="2017-08-21T09:08:19Z" finished-at="2017-08-21T09:08:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20737" started-at="2017-08-21T09:08:19Z" finished-at="2017-08-21T09:08:40Z">
      <class name="TestCases.Reg_TC">
        <test-method status="PASS" signature="beforeexecution(java.lang.String)[pri:0, instance:TestCases.Reg_TC@d5c04e]" name="beforeexecution" is-config="true" duration-ms="5202" started-at="2017-08-21T14:38:19Z" finished-at="2017-08-21T14:38:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeexecution -->
        <test-method status="FAIL" signature="testmethod()[pri:0, instance:TestCases.Reg_TC@d5c04e]" name="testmethod" duration-ms="13132" started-at="2017-08-21T14:38:24Z" finished-at="2017-08-21T14:38:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for your registration] but found [Error: Username already exists]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for your registration] but found [Error: Username already exists]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestModules.RegistrationActions.execute(RegistrationActions.java:183)
	at TestCases.Reg_TC.testmethod(Reg_TC.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Verify whether the registration buttion is displayed at right pannel top]]>
            </line>
            <line>
              <![CDATA[Registration buttion is successfully displayed at right pannel top]]>
            </line>
            <line>
              <![CDATA[Registration buttion is successfully clicked at right pannel top]]>
            </line>
            <line>
              <![CDATA[Without enter values in all the fields and clicked on submit button successfully]]>
            </line>
            <line>
              <![CDATA[Mandatory fields alert messages are successfully displayed]]>
            </line>
            <line>
              <![CDATA[Enter values in all the fields and clicked on submit button successfully]]>
            </line>
            <line>
              <![CDATA[Successfully Clicked on submit button]]>
            </line>
            <line>
              <![CDATA[Registration done successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testmethod -->
        <test-method status="PASS" signature="afterexecution()[pri:0, instance:TestCases.Reg_TC@d5c04e]" name="afterexecution" is-config="true" duration-ms="2387" started-at="2017-08-21T14:38:37Z" finished-at="2017-08-21T14:38:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterexecution -->
      </class> <!-- TestCases.Reg_TC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
